Fixed typeerror in squire
When SVGs were being clicked, the squire editor caused an error "TypeError: node.className.trim is not a function".
Now there is a simple check for if className is actually in node.

Fixes #148